# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0001_initial'),
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaIngrediente',
            fields=[
                ('id_aula_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_projetada_aula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_utilizada_aula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aula', to='aulas.Aula')),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingrediente', to='ingredientes.Ingrediente')),
            ],
        ),
    ]
