# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('data_aula', models.DateField(default='01 de janeiro de 2000', null=True)),
                ('descricao_aula', models.CharField(max_length=200)),
                ('aula_agendada', models.BooleanField(default=True)),
                ('aula_concluida', models.BooleanField(default=True)),
                ('periodo_aula', models.CharField(max_length=100, null=True)),
                ('numero_de_alunos_projetados_aula', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(50)])),
            ],
        ),
    ]
