# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0001_initial'),
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaReceita',
            fields=[
                ('id_aula_receita', models.AutoField(primary_key=True, serialize=False)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aula_Receita', to='aulas.Aula')),
                ('id_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receita', to='receitas.Receita')),
            ],
        ),
    ]
