# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id_unidade_medida', models.AutoField(primary_key=True, serialize=False)),
                ('simbolo_unidade_medida', models.CharField(max_length=4)),
                ('descricao_unidade_medida', models.CharField(max_length=20)),
            ],
        ),
    ]
